language: python
python:
- '3.5'
install:
- pip install .
script:
- python -m doctest -v README.md
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: rIFvFpdkxSDktSHJaO4h69Zr70o4ChU2l6YlZiou1INVlyWkTGcwI4FdJ4Xdo7PGF188mWH8gk8nfiUwPq8U0YV07e0kXCiCGmCixQJBlBYSEWZIXa6wgyh9BDwZL1Ca9kBkV1wyTYT0fbUR68+Zvpx5SIqQGhyiZlLEDhqAN4CopzYI5NNTGu4ayBLyMcQorQlV6K8Knm6cKxaf3MXK+3iDvyYDkUteiDo7UPd/D8fsGhDPHZKOR260UiVfFrFE1ef8RuxG01G2Y+Bv+nR9hYhLV030D9nwAEjnlCvG9mRx0Sw44ptsNPar34mtr7XAPjnTgcVa7hhyLKgXeoyhijQ1rJIcBDYUMQa3S+Wm0JDe0tXUVVfc3kpZMUrH4mIVvG4y7HlKRc85U3CQoe7PJAxNqbsNfZuWVLzPO6CEYjdUQuf7SQk3XlSTcKRBZ5f2QgXFNFyzc29h1Ld6WDwwFcMsaiJhr9bYdIMSeuJFRkq//W3s++S0nx5D9vEqp11+4QZVBnk9qBOUxVMKBjEXz6J54v3gMLfUu0hoY/eu66Y1PIkp+g5Lfb9KLpcSS6d7vLNgkhtqcuXZtZ02sGvSPIbowN/aoi8SqKqcNbNkE00YkkvyFdKoWi05C6uUsQqnbMrWYv0sGdjKIuuPf/aQitepH3UX5dxFuJA7MJ/sz6g=
  file:
    - README.md
    - setup.py
    - LICENSE
    - kwikapi/api.py
    - kwikapi/__init__.py
  name: kwikapi-0.0.1
  tag_name: 0.0.1
  on:
    repo: deep-compute/kwikapi
- provider: pypi
  distributions: "sdist bdist_wheel"
  server: https://testpypi.python.org/pypi
  user: deepcompute
  password:
    secure: vZ1JZchFnvnvgbqGJ4YQto32DjV2z32MlkVnFlGaXMC6bwfnpVw8F17PG0WVjd2vP0Rt5yIEpyu6CwE5NnhsPOZN00lQVHf0xAZboqAodYgnaStqYlr+Y0mtvg+v/i9+1QgnXdB4sJoZP92BAULCDlC0CHmzn1yCrVh4pan5nXheWTBVWv2RN4QllQm5Ksvf2bWj6aW6xpmWHmtyK3T1J8DxjXKRCL8YWfkrYsganfDtf2Y1lAVSZjMMSN4MDC7o56jf6unEABfjmRNvqdGUeY+kPaKCItONRf67INaYE2YI13W9kD+8nVAbhhRQoZyZTjQenwXqnENUIaNz1ED3idHVDLCOfPCGd98B2TrAmi/lbqB65uqxna1zmtiF4GJmuzEndW0jzKtHovMnoqcql9e8oUNvGegxpjocvxzBl8ty6sHblULmpw/TRzlqnVplJrul6BhKK2P+OLCGTvSWAR+uZlNaYV9HshIEZfTjDdLn1PcECVrmJAyhx0iPF09U662QsYE+eWPXkwMeehQp5CZE9gJgCanCrFVhX09rBj2o3YhxV7xJJchwIT4H/1KGOTu7IWd2GcJzHIsD4woSjaTQvdUPKzRPBUxglWE7sMXq/KLrWoDoUM1Fys7ltu+0Sp0QXMELOolN+eVinnNuknKAQY50TRpBAnmlbAUu8YA=
  on:
    tags: false
    branch: master
- provider: pypi
  distributions: "sdist bdist_wheel"
  server: https://upload.pypi.org/legacy/
  user: deepcompute
  password:
    secure: vZ1JZchFnvnvgbqGJ4YQto32DjV2z32MlkVnFlGaXMC6bwfnpVw8F17PG0WVjd2vP0Rt5yIEpyu6CwE5NnhsPOZN00lQVHf0xAZboqAodYgnaStqYlr+Y0mtvg+v/i9+1QgnXdB4sJoZP92BAULCDlC0CHmzn1yCrVh4pan5nXheWTBVWv2RN4QllQm5Ksvf2bWj6aW6xpmWHmtyK3T1J8DxjXKRCL8YWfkrYsganfDtf2Y1lAVSZjMMSN4MDC7o56jf6unEABfjmRNvqdGUeY+kPaKCItONRf67INaYE2YI13W9kD+8nVAbhhRQoZyZTjQenwXqnENUIaNz1ED3idHVDLCOfPCGd98B2TrAmi/lbqB65uqxna1zmtiF4GJmuzEndW0jzKtHovMnoqcql9e8oUNvGegxpjocvxzBl8ty6sHblULmpw/TRzlqnVplJrul6BhKK2P+OLCGTvSWAR+uZlNaYV9HshIEZfTjDdLn1PcECVrmJAyhx0iPF09U662QsYE+eWPXkwMeehQp5CZE9gJgCanCrFVhX09rBj2o3YhxV7xJJchwIT4H/1KGOTu7IWd2GcJzHIsD4woSjaTQvdUPKzRPBUxglWE7sMXq/KLrWoDoUM1Fys7ltu+0Sp0QXMELOolN+eVinnNuknKAQY50TRpBAnmlbAUu8YA=
  on:
    tags: true
    branch: master
